# Generated by Django 3.2 on 2021-05-02 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('director', models.CharField(max_length=120)),
                ('genre', models.CharField(max_length=120)),
                ('rating', models.IntegerField()),
                ('release_data', models.DateField()),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
